dependencies:
- condition: activiti-cloud-modeling.enabled,modeling.enabled
  name: activiti-cloud-modeling
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.6.0
- name: application
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.6.0
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.88
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.88
- name: infrastructure
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.6.0
